### ISSUE TITLE
I want use two_factor without otp_yubikey

### ISSUE THREAD

**Issue by byYuraGudan** [Bouke/django-two-factor-auth#356] opened 2020-05-07 08:32 UTC
I have problem, with RuntimeError

## Error
  File "/home/yuragudan/datawiz/OAuth/backend/oauth2/urls.py", line 5, in <module>
    from . import views
  File "/home/yuragudan/datawiz/OAuth/backend/oauth2/views.py", line 9, in <module>
    from two_factor.views import OTPRequiredMixin
  File "/home/yuragudan/datawiz/.venv/OAuth/lib/python3.8/site-packages/two_factor/views/__init__.py", line 1, in <module>
    from .core import (
  File "/home/yuragudan/datawiz/.venv/OAuth/lib/python3.8/site-packages/two_factor/views/core.py", line 40, in <module>
    from otp_yubikey.models import ValidationService, RemoteYubikeyDevice
  File "/home/yuragudan/datawiz/.venv/OAuth/lib/python3.8/site-packages/otp_yubikey/models.py", line 35, in <module>
    class YubikeyDevice(Device):
  File "/home/yuragudan/datawiz/.venv/OAuth/lib/python3.8/site-packages/django/db/models/base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class otp_yubikey.models.YubikeyDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

## Steps to Reproduce (for bugs)
Following the instructions on the site `https://django-two-factor-auth.readthedocs.io/en/stable/installation.html`,  I made installation steps without Setup Yubikey, since I do not need it. But when I run the application, it throws errors, since you surely need to put in INSTALLED_APPS yubikey.

## Context
Can I use the library without otp_yubikey ?

## Your Environment

* Browser and version: Google
* Python version: 3.8
* Django version: 3.0.6
* django-otp version: 0.9.0
* django-two-factor-auth version: 1.11.0

**Comment by moggers87** [comment] 2020-05-07 12:59
I can't reproduce this with my own projects, though I am using Django 2.2.

Can you tell me what's in your `INSTALLED_APPS` setting?

Also can you run `./manage.py shell` and tell me the output of the following:

   import two_factor.views.core

**Comment by byYuraGudan** [comment] 2020-05-11 09:02
1. 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'backend.oauth2',
    'backend.accounts',
    'backend.db.postgresql.client',
    'backend.db.postgresql.authorize',
    'django_extensions',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    # 'otp_yubikey',
]
2. 
import two_factor.views.core                                                                                                                                                                                           
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-5834ec6a0d9e> in <module>
----> 1 import two_factor.views.core

~/datawiz/.venv/OAuth/lib/python3.8/site-packages/two_factor/views/__init__.py in <module>
----> 1 from .core import (
      2     BackupTokensView, LoginView, PhoneDeleteView, PhoneSetupView,
      3     QRGeneratorView, SetupCompleteView, SetupView,
      4 )
      5 from .mixins import OTPRequiredMixin

~/datawiz/.venv/OAuth/lib/python3.8/site-packages/two_factor/views/core.py in <module>
     29 from two_factor.utils import totp_digits
     30 
---> 31 from ..forms import (
     32     AuthenticationTokenForm, BackupTokenForm, DeviceValidationForm, MethodForm,
     33     PhoneNumberForm, PhoneNumberMethodForm, TOTPDeviceForm, YubiKeyDeviceForm,

~/datawiz/.venv/OAuth/lib/python3.8/site-packages/two_factor/forms.py in <module>
     16 
     17 try:
---> 18     from otp_yubikey.models import RemoteYubikeyDevice, YubikeyDevice
     19 except ImportError:
     20     RemoteYubikeyDevice = YubikeyDevice = None

~/datawiz/.venv/OAuth/lib/python3.8/site-packages/otp_yubikey/models.py in <module>
     33 
     34 
---> 35 class YubikeyDevice(Device):
     36     """
     37     Represents a locally-verified YubiKey OTP

~/datawiz/.venv/OAuth/lib/python3.8/site-packages/django/db/models/base.py in __new__(cls, name, bases, attrs, **kwargs)
    110             if app_config is None:
    111                 if not abstract:
--> 112                     raise RuntimeError(
    113                         "Model class %s.%s doesn't declare an explicit "
    114                         "app_label and isn't in an application in "

RuntimeError: Model class otp_yubikey.models.YubikeyDevice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by moggers87** [comment] 2020-05-11 12:59
Oh, do you have `django-otp-yubikey` installed? If you do, uninstalling it should fix your issue.

**Comment by byYuraGudan** [comment] 2020-05-11 14:03
@moggers87, thanks. That`s works ))

**Comment by moggers87** [comment] 2020-05-13 11:44
Closing this issue as it appears to be solved

**Closed by moggers87** 2020-05-13 11:44 UTC
