### ISSUE TITLE
Unable to use applications that are not google authenticator

### ISSUE THREAD

**Issue by jakob223** [Bouke/django-two-factor-auth#103] opened 2015-06-12 21:21 UTC
I have tried the following applications with your example site (and my application in which I use your  package).
- Microsoft Authenticator (windows phone)
- Cloake Token (android)
- TOTP authenticator (android)

They all error, which is unfortunate.

However, google authenticator works fine for me (on my site). All these applications say that the QR code is invalid - does this package and/or google authenticator deviate from the standard?

**Comment by Bouke** [comment] 2015-06-13 09:46
I have tried to replicate with the following apps on my iPhone on the example site:

* Google Authenticator: success, generates 8-digit codes
* HDE-OTP: scanning QR code works, but failing because it generates 6-digit codes instead of 8-digit

The OTP-url that is currently used, taken from localhost:

    otpauth://totp/localhost%3A8000%3A%20bouke?digits=6&secret=[...]&issuer=localhost%3A8000

For the specification of this URL, see also [Key Uri Format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).

It seems that not all apps support the full specification of OTP-tokens. Some apps will always use 30-second windows and generate 6-digit codes. I've updated the example site to just use a 30-second window. Could you try again now?

**Comment by austintrose** [comment] 2015-06-26 20:56
Hey @Bouke - I'm with @jake223 here. Sorry about such a delay, but for the record we are still unable to use any apps other than the Google Authenticator. We have tried all three alternative apps above on your example site to no avail. 

Thanks for taking the time to look at this!

**Comment by Bouke** [comment] 2015-08-16 05:56
Could you try a few variations of the OTP-url, as I don't have access to an Android / Windows Phone? The code resides in https://github.com/Bouke/django-two-factor-auth/blob/2d1145f03ed80d833e9527df4485b9f0d53279a1/two_factor/utils.py#L27-L46. So you could try removing these two lines:

    if issuer:
        query['issuer'] = issuer

Then, hardcode the accountname:

    accountname = b"test"

And, hardcode the issuer:

    issuer = b"test"

**Comment by clokep** [comment] 2015-08-19 19:34
I spent a few minutes playing with this today on a Windows phone. Hardcoding the `issuer` and `accountname` to `b"test"` display the same errors. I did hard code the returned URI to what Google provides in [their documentation](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) and that worked fine (leaving me to believe it's something with how the URI is generated and *not* how it is rendered).

I also took a brief look at [cryptography's new `get_provisioning_uri` method](https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/twofactor/utils.py), but didn't spot any obvious differences.

**Comment by Bouke** [comment] 2015-08-22 05:38
Have you tried hardcoding the label to `Example:alice@google.com`? Could you find out the difference between Google's working example URL and the failing URL in the package? That would help a lot.

**Comment by clokep** [comment] 2015-08-24 12:33
I did try that, the account name appears correctly in my application (and always has), the issue is that the key doesn't appear.

Investigating further:
* Directly entering the hex generated key into Microsoft Authenticator works!
* Removing the parameter `digits` causes it to work!
* Attempting to use more than 6 digits (e.g. 8) truncates to 6 digits in Microsoft Authenticator.
* Feeding the `secret` parameter as the first in the URI works! It seems that Microsoft Authenticator *wants* the `secret` to be the first parameter. It might just ignore parameters after that?

The following diff allows Microsoft Authenticator to work (I can turn this into a PR, if you'd like.)

```diff
diff --git a/two_factor/utils.py b/two_factor/utils.py
index e4a2a09..cc1a668 100644
--- a/two_factor/utils.py
+++ b/two_factor/utils.py
@@ -35,13 +35,15 @@ def get_otpauth_url(accountname, secret, issuer=None, digits=None):
 
     label = quote(b': '.join([issuer, accountname]) if issuer else accountname)
 
-    query = {
-        'secret': secret,
-        'digits': digits or totp_digits()
-    }
+    # Ensure that the secret parameter is the FIRST parameter of the URI, this
+    # allows Microsoft Authenticator to work.
+    query = [
+        ('secret', secret),
+        ('digits', digits or totp_digits())
+    ]
 
     if issuer:
-        query['issuer'] = issuer
+        query.append(('issuer', issuer))
 
     return 'otpauth://totp/%s?%s' % (label, urlencode(query))
 
```

(Note that "The order of parameters in the encoded string will match the order of parameter tuples in the sequence." when using [`urlencode`](https://docs.python.org/2/library/urllib.html#urllib.urlencode), unfortunately the ordering from a `dict` is arbitrary, feeding in an iterable of tuples ensures that `secret` is first.)

Thanks for the pointers in figuring this out! Note that I was unable to test on anything besides Microsoft Authenticator after this change.

**Comment by Bouke** [comment] 2015-10-03 21:22
Thanks @clokep, I've merged your fix in 3af3fc3012da5d4fd8acf4c0a98a260480f6bbe2. @jake223 can you retest the fix in master?

**Comment by Bouke** [comment] 2016-11-03 19:22
Closing as no follow-up has been posted in over a year.

**Closed by Bouke** 2016-11-03 19:22 UTC
Labels: bug

**Comment by clokep** [comment] 2016-11-03 19:26
@Bouke Sorry no one ever got back to you. This now works fine with Microsoft Authenticator.
