### ISSUE TITLE
required token field prevents clicking on "Use Backup Token" button

### ISSUE THREAD

**Issue by tecknicaltom** [Bouke/django-two-factor-auth#91] opened 2015-04-07 22:34 UTC
When at the prompt for a token, if backup tokens exist, the page includes a button labeled "Use Backup Token". However, because the primary token input field (id=id_token-otp_token) is marked as required, the user is not able to click on this button to use a backup token unless they enter something into the token field.

Tested with Firefox 31.3.0 and django-two-factor-auth==1.1.1

**Comment by Bouke** [comment] 2015-04-10 18:44
I feel like this is a bug with the current implementation. I don't think the button for using a backup token should be part of the form, which is currently causing this issue.

**Comment by Bouke** [comment] 2015-04-15 15:36
I'm trying to reproduce this issue, but no success. I've tried with Firefox 36, 37, Safari 8 and Chrome 41 (all on OS X). Can you maybe share some more information? If the issue is related to the older version of Firefox you're using, I'll probably close this as won't fix.

**Comment by tecknicaltom** [comment] 2015-04-16 22:31
I've tracked this down to the fact that the server that exhibited this behavior was running an old Django (1.5.1). I'm not sure what version changed the widget for forms.IntegerField, but feel free to close the issue if that's older than you'd like to support.

**Closed** 2015-04-17 05:37 UTC
Labels: bug
