### ISSUE TITLE
Error accesing to enable two-factor

### ISSUE THREAD

**Issue by Kailegh** [Bouke/django-two-factor-auth#337] opened 2020-02-22 11:17 UTC
Hi, I have been trying to enable two factor authentification in my project, since I could not get it to work I decided to just try to run the example, however I am getting the same error.

When click on activate two factor and select the code generator I get the following error:
```
key = random_hex(20).decode('ascii')
AttributeError: 'str' object has no attribute 'decode'
ERROR 2020-02-22 12:12:46,484 django.server basehttp "POST /account/two_factor/setup/?next=/S2T/ HTTP/1.1" 500 148201
2020-02-22 12:12:46,484 ERROR "POST /account/two_factor/setup/?next=/S2T/ HTTP/1.1" 500 148201
```

I have been trying to run the code in python3.6 and 3.7 with the same results.
I have not made any change in the code, just trying to run the example.

Do you have any idea of what could I be doing wrong?

Thanks a lot!

**Comment by claudep** [comment] 2020-02-22 11:28
Yes, this is a known problem (see #335).

@Bouke, would be great if I could have perms to triage issues.

**Comment by moggers87** [comment] 2020-02-22 11:31
duplicate of #335

**Closed by moggers87** 2020-02-22 11:31 UTC
