### ISSUE TITLE
Error when migrating after setting up django-two-factor-auth

### ISSUE THREAD

**Issue by nanduajith** [Bouke/django-two-factor-auth#339] opened 2020-02-27 16:37 UTC
## Expected Behavior
The Migration should happen without any error.

## Current Behavior
Iam getting the following error when migrating:

Applying otp_static.0001_initial... OK
  Applying otp_totp.0001_initial... OK
  Applying otp_totp.0002_auto_20190420_0723... OK
  Applying two_factor.0001_initial... OK
  Applying two_factor.0002_auto_20150110_0810... OK
  Applying two_factor.0003_auto_20150817_1733... OK
  Applying two_factor.0004_auto_20160205_1827... OK
  Applying two_factor.0005_auto_20160224_0450... OK
  Applying two_factor.0006_phonedevice_key_default...Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 564, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 152, in _alter_field
    super()._alter_field(
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 679, in _alter_field
    new_default = self.effective_default(new_field)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 303, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 282, in _effective_default
    default = field.get_default()
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 829, in get_default
    return self._get_default()
  File "/Users/nandu.ajith/mits/lib/python3.8/site-packages/two_factor/models.py", line 57, in random_hex_str
    return random_hex().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

## Possible Solution
Changing **"return random_hex().decode('utf-8')"** to **"return random_hex()"**  solved the migration issue.

## Your Environment

* Python version:  3.8.1
* Django version: 3.0.3
* django-otp version: 0.8.1
* django-two-factor-auth version: 1.10.0

**Comment by debdolph** [comment] 2020-02-27 20:10
Duplicate of #335

**Closed** 2020-02-29 00:06 UTC
