### ISSUE TITLE
Update translations on transifex

### ISSUE THREAD

**Issue by leo-naeka** [Bouke/django-two-factor-auth#411] opened 2021-02-24 09:11 UTC
Could you please consider pushing updated translations on Transifex?

Last upload was on July, 8 and misses strings from the "remember browser" feature for example.

**Comment by claudep** [comment] 2021-02-25 07:54
That's a duplicate of #353, Transifex should be configured to automatically retrieve the latest `en//LC_MESSAGES/django.po` file from GitHub.

**Comment by moggers87** [comment] 2021-02-25 10:21
Closing in favour of #353 and thanks for the reminder that we still need to do that :+1:

**Closed by moggers87** 2021-02-25 10:21 UTC
