### ISSUE TITLE
Call Gateway Non-Functional

### ISSUE THREAD

**Issue by jjorissen52** [Bouke/django-two-factor-auth#282] opened 2018-09-07 17:33 UTC
Call Gateway gives `django.urls.exceptions.NoReverseMatch: 'two_factor_twilio' is not a registered namespace` after submitting a phone numbers.

## Expected Behavior
It should call me.

## Current Behavior
Traceback below. SMS Gateway and Token authenticator both work fine.

```
Could not generate challenge
Traceback (most recent call last):
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/django/urls/base.py", line 77, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'two_factor_twilio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/two_factor/views/core.py", line 274, in render_next_step
    self.get_device().generate_challenge()
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/two_factor/models.py", line 114, in generate_challenge
    make_call(device=self, token=token)
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/two_factor/gateways/__init__.py", line 11, in make_call
    gateway.make_call(device=device, token=token)
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/two_factor/gateways/twilio/gateway.py", line 53, in make_call
    url = reverse('two_factor_twilio:call_app', kwargs={'token': token})
  File "/home/jp/Projects/venvs/portal_dev/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'two_factor_twilio' is not a registered namespace
```

## Steps to Reproduce (for bugs)
1. python 3.6.5
2. You can download a repro setup at https://github.com/jjorissen52/bug_reproduction. Instructions in the readme.

## Context
I'm trying to implement two-factor auth for a web application for internal use. Not being able to use the call gateway is not a deal breaker, but I'd still like for it to be available.

## Your Environment
* Python version: 3.6.5
* all other relevant details should be in the project on github.

**Comment by moggers87** [comment] 2018-09-09 12:50
Looks like you missed out on including the Twilio URLs and required middleware: https://django-two-factor-auth.readthedocs.io/en/stable/configuration.html#twilio-gateway

**Comment by moggers87** [comment] 2018-09-09 12:58
Here's a diff for your example repo:

```
diff --git a/call_gateway_bug/urls.py b/call_gateway_bug/urls.py
index ca2ad97..44cef8c 100644
--- a/call_gateway_bug/urls.py
+++ b/call_gateway_bug/urls.py
@@ -16,8 +16,10 @@ Including another URLconf
 from django.conf.urls import url, include
 from django.contrib import admin
 from two_factor.urls import urlpatterns as tf_urls
+from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

 urlpatterns = [
     url('admin/', admin.site.urls),
     url(r'', include(tf_urls)),
-]
\ No newline at end of file
+    url(r'', include(tf_twilio_urls)),
+]
```

Going to close this as it appear to be not a bug.

**Closed by moggers87** 2018-09-09 12:58 UTC

**Comment by jjorissen52** [comment] 2018-09-10 13:45
Hey, sorry about that. I do have those things included on my actual project, I just goofed it on the reproduction. I've updated the reproduction project to include the changes to the middleware and included the urls. Any help would be appreciated.

```
Could not generate challenge
Traceback (most recent call last):
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/two_factor/views/core.py", line 274, in render_next_step
    self.get_device().generate_challenge()
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/two_factor/models.py", line 114, in generate_challenge
    make_call(device=self, token=token)
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/two_factor/gateways/__init__.py", line 11, in make_call
    gateway.make_call(device=device, token=token)
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/two_factor/gateways/twilio/gateway.py", line 58, in make_call
    url=uri, method='GET', timeout=15)
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/twilio/rest/api/v2010/account/call/__init__.py", line 119, in create
    data=data,
  File "/home/jp/Projects/venvs/venv_call_gateway_bug/lib/python3.6/site-packages/twilio/base/version.py", line 209, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: Url is not a valid url: http://localhost:8000/twilio/inbound/two_factor/309495/?locale=en-us

```

**Comment by moggers87** [comment] 2018-09-10 15:17
That's a response from the Twilio server. Twilio uses webhooks to talk to your application and that means it needs to be given a URL it can actually request, which it can't do for `localhost`.

As your web application is for internal use, it might be impossible to use Twilio.

**Comment by jjorissen52** [comment] 2018-09-10 15:28
That makes perfect sense. I'll try it on a real domain.
